### ISSUE TITLE
embeddedterminal cannot handle command with double quotes

### ISSUE THREAD

**Issue by Scimmia22** [JeffHoogland/python-elm-extensions#4]
When trying to run a command with a double quote in it, I just get:

```
Error: bash: line 1: quot: command not foundbash: line 1: quot: command not found
```

**Comment by JeffHoogland** [comment]
Works here in 2.7.5:

https://www.enlightenment.org/ss/e-54d1a60221e503.43044647.jpg

**Comment by Scimmia22** [comment]
Fails here with 2.7.9 and 3.4.2. Could it be in the shell configuration?

**Comment by JeffHoogland** [comment]
Perhaps. I'm using bash 4.3 here. Where are the config files for that at?

**Comment by Scimmia22** [comment]
Mostly in ~/.bash_profile and ~/.bashrc. There are most likely some global configs in /etc, but that will be  distro dependent (/etc/bash.bashrc here). For the record, it's happening here with both bash 4.3.033 and zsh 5.0.7

**Comment by Scimmia22** [comment]
OK, I just downgraded to python 2.7.5 to test, no difference. I'm thinking it has to be something shell related.

**Comment by Scimmia22** [comment]
More info, by adding a print to line 56, I see that running echo "test" becomes echo &quot;test&quot; which the shell can't interpret correctly.

**Comment by rbtylee** [comment]
Commit 2cad9a0 address this issue. Let us know if this fixes your issue, Scimmia22

**Comment by Scimmia22** [comment]
Two and a half years later, I"m not doing anything with EFL or python-elm-extensions. No idea if that fixes anything.

**Comment by rbtylee** [comment]
No Problem Scimmia22. I didn't know if you did or not and I only recently started working/looking at this code. Trying to find issues, close existing ones or add new features.
