### ISSUE TITLE
New Tag/release

### ISSUE THREAD

**Issue by wltjr** [JeffHoogland/python-elm-extensions#8]
I know there have only been minor commits since the last tag/release. Could a new one be done? Thanks!

**Comment by rbtylee** [comment]
I tagged [release 0.2.1, Swallow's Tail](https://github.com/JeffHoogland/python-elm-extensions/releases/tag/0.2.1). We have some major commits and a new font dialog in the works as soon as I get to cleaning up my code and committing it. Python-elm-extensions and epad in Bodhi's repo already use it. Completely unsure at the this point when I will have a free day or more to work on refactoring the font dialog. But when I do I will tag a new release.

**Comment by wltjr** [comment]
Thanks, no worries. Tags are easier for packaging than git hashes. I cannot really version a package with a git hash. I have to put that internal, and make up some external version, usually tag date. Where as versions, I have a [script](https://github.com/Obsidian-StudiosInc/ebuild-bumper/) to do the update saving me some time.

**Comment by wltjr** [comment]
I see this was already tagged, not sure why I asked for a new tag guess anxious, but thanks... :)

**Comment by rbtylee** [comment]
Minor fix in latest release
